# -*- coding: utf-8 -*-
"""tp . maths

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kx2ZZDDJkzQYy2OniRF_cjl-vag56-Ft
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuration pour que les graphiques s'affichent bien dans Colab
# %matplotlib inline
sns.set_theme(style="whitegrid") # Style "pro" par défaut

np.random.seed(42)
n = 1000
data = {
    'math_score': np.random.normal(66, 15, n).clip(0, 100),
    'reading_score': np.random.normal(69, 14, n).clip(0, 100),
    'writing_score': np.random.normal(68, 15, n).clip(0, 100),
    'test_preparation': np.random.choice(['none', 'completed'], n, p=[0.6, 0.4]),
    'lunch': np.random.choice(['standard', 'free/reduced'], n)
}
df = pd.DataFrame(data)

plt.figure(figsize=(8, 5))
sns.histplot(df['math_score'], kde=True, color='skyblue', bins=30)
plt.title('Distribution des Scores de Mathématiques')
plt.xlabel('Note / 100')
plt.ylabel('Nombre d\'élèves')
plt.show()



plt.figure(figsize=(6, 6))
sns.boxplot(y=df['math_score'], color='lightgreen', width=0.3)
plt.title('Détection des Outliers (Maths)')
plt.ylabel('Score')
plt.show()

plt.figure(figsize=(8, 6))
# C'est ici qu'il y avait l'erreur de parenthèse !
sns.regplot(x='reading_score', y='writing_score', data=df,
            scatter_kws={'alpha':0.3, 'color':'gray'},
            line_kws={'color':'red'})

plt.title('Lien entre Lecture et Écriture')
plt.xlabel('Score Lecture')
plt.ylabel('Score Écriture')
plt.show()

corr_matrix = df[['math_score', 'reading_score', 'writing_score']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Matrice de Corrélation de Pearson')
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(x='test_preparation', y='math_score', data=df, palette='viridis')
plt.title('Impact de la préparation sur le score de Maths')
plt.show()