# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpFmsgXEmMlesEtNx4sXrQapfSn6WsIy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

"""## telechargement de notre dataset (source :kaggle)"""

data = pd.read_csv("/content/Personal_Finance_Dataset.csv")

data.info()

data.head()

data.describe()

data['Date'] = pd.to_datetime(data['Date'])

data['Month'] = data['Transaction Description\t'].dt.month
data['Year'] = data['Transaction Description\t'].dt.year

nan_count=data.isnull().sum()
nan_pct=(nan_count/len(data)*100).round(2)
data_nan= pd.concat([nan_count,nan_pct],axis=1)
data.columns=["Transaction Description	","Type","Category","Amount","Date"]
data_nan.head()

print(data.isnull().sum())

n_dup=data.duplicated().sum()
print(f"nombre de doublantv:",{n_dup})

data.dropna(inplace=True)

"""## encoding"""

data['Category_Code'] = data['Category'].astype('category').cat.codes

"""outliers"""

Q1 = data["Amount"].quantile(0.25)
Q3 = data["Amount"].quantile(0.75)
iqr = Q3 - Q1
lower_bound=Q1-1.5*iqr
upper_bound=Q3+1.5*iqr


data_clean = data[(data["Amount"] > lower_bound) | (data["Amount"] < upper_bound)]
print(f"borne inférieure:{lower_bound:.2f}|borne supérieure:{upper_bound:.2f}")

"""##visualisation de données"""

plt.figure(figsize=(10,6))
sns.barplot(x='Category', y='Amount', data=data, estimator=np.sum)

plt.title("Total Spending by Category")
plt.xticks(rotation=45)
plt.show()

monthly = data.groupby('Month')['Amount'].sum()

plt.figure(figsize=(8,5))
monthly.plot(kind='line', marker='o')

plt.title("Monthly Spending Trend")
plt.xlabel("Month")
plt.ylabel("Total Amount")

plt.show()

"""##machin learning model

## featurs
"""

X = data[['Month','Category_Code']]
y = data['Amount']

"""##training test"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""##training"""

model = RandomForestRegressor(n_estimators=100)

model.fit(X_train, y_train)

"""##prediction"""

predictions = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, predictions))

print("Model RMSE:", rmse)

"""## predivtion de futurspending

"""

future_data = pd.DataFrame({
    "Month":[6,6,6],
    "Category_Code":[0,1,2]
})

future_predictions = model.predict(future_data)

print("Predicted Spending:", future_predictions)

"""## visualisation de prediction"""

plt.scatter(y_test, predictions)

plt.xlabel("Real Values")
plt.ylabel("Predicted Values")
plt.title("Real vs Predicted Spending")

plt.show()

"""##Visualization of Regression Results"""

fig, ax = plt.subplots(figsize=(11,6))

# Real values
ax.scatter(y_test, predictions, # Changed y_pred to predictions
           color="steelblue",
           alpha=0.7,
           s=50,
           label="Prédictions du modèle")

# Perfect prediction line
ax.plot([y_test.min(), y_test.max()],
        [y_test.min(), y_test.max()],
        color="red",
        linewidth=3,
        label="Prédiction parfaite")

ax.set_xlabel("Dépenses réelles (MAD)")
ax.set_ylabel("Dépenses prédites (MAD)")
ax.set_title("Prédiction des dépenses avec le modèle ML", fontsize=14, fontweight="bold")

ax.legend(fontsize=11)

plt.show()