# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bx3HXYQN0k0d5RQ44jLkTAvRYtk4C2UZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/StudentsPerformance.csv")

scores = ["math score", "reading score", "writing score"]

df.head()
df[scores].describe()

mean_ = df[scores].mean()
median_ = df[scores].median()
mode_ = df[scores].mode()

pd.DataFrame({
    "Moyenne": mean_,
    "Médiane": median_,
    "Mode": mode_.iloc[0]
})

range_ = df[scores].max() - df[scores].min()
range_

var_pop = df[scores].var(ddof=0)
std_pop = df[scores].std(ddof=0)

pd.DataFrame({
    "Variance": var_pop,
    "Ecart-type": std_pop
})

q1 = df[scores].quantile(0.25)
q2 = df[scores].quantile(0.50)
q3 = df[scores].quantile(0.75)
iqr = q3 - q1

pd.DataFrame({
    "Q1": q1,
    "Q2": q2,
    "Q3": q3,
    "IQR": iqr
})

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

pd.DataFrame({
    "Borne inf": lower,
    "Borne sup": upper
})

for col in scores:
    mask = (df[col] < lower[col]) | (df[col] > upper[col])
    print(col, mask.sum())

for col in scores:
    plt.figure()
    plt.hist(df[col], bins=15)
    plt.title(col)
    plt.show()

plt.figure()
plt.boxplot([df["math score"], df["reading score"], df["writing score"]])
plt.xticks([1,2,3], ["Math", "Reading", "Writing"])
plt.show()

plt.figure()
plt.bar(["Math", "Reading", "Writing"], mean_.values)
plt.show()

plt.figure()
plt.bar(["Math", "Reading", "Writing"], mean_.values)
plt.show()

corr = df[scores].corr()
corr

plt.figure()
plt.imshow(corr.values)
plt.xticks(range(3), ["Math", "Reading", "Writing"])
plt.yticks(range(3), ["Math", "Reading", "Writing"])
plt.colorbar()
plt.show()

df.groupby("gender")[scores].mean()

df.groupby("test preparation course")[scores].mean()

df.groupby("lunch")[scores].mean()

df.groupby("parental level of education")[scores].mean()

pd.plotting.scatter_matrix(df[scores])
plt.show()